import type { ActivityEvent } from '@/data/activity/activityStream';
import { companyData } from '@/data/company';
import { defaultSeo } from '@/utils/seo/staticSeo';

import { ORGANIZATION_ID, SCHEMA_CONTEXT, buildAbsoluteUrl } from './helpers';
import type { DataFeedItemSchema, DataFeedSchema, PropertyValueSchema } from './types';

const FEED_ID = `${defaultSeo.canonical}#live-activity-feed`;
const TIME_AGO_REGEX = /^(?:\d+)(?:[smhd])?\s*(?:ago)?$/;
const TIME_AGO_PARSE_REGEX = /^(\d+)([smhd])?/;

function parseTimeAgo(timeAgo: string): { value: number; unit: string } | null {
	const trimmed = timeAgo.trim().toLowerCase();
	if (!trimmed) return null;

	const match = trimmed.match(TIME_AGO_PARSE_REGEX);
	if (!match) return null;

	const value = Number.parseInt(match[1] ?? '', 10);
	if (Number.isNaN(value)) {
		return null;
	}

	const unit = match[2] ?? 'm';
	return { value, unit };
}

function timeAgoToIso(timeAgo: string): string | undefined {
	if (!timeAgo) {
		return undefined;
	}
	if (!TIME_AGO_REGEX.test(timeAgo.trim().toLowerCase())) {
		return undefined;
	}
	const parsed = parseTimeAgo(timeAgo);
	if (!parsed) return undefined;

	const { value, unit } = parsed;
	const now = Date.now();
	let delta = 0;

	switch (unit) {
		case 's':
			delta = value * 1000;
			break;
		case 'h':
			delta = value * 60 * 60 * 1000;
			break;
		case 'd':
			delta = value * 24 * 60 * 60 * 1000;
			break;
		default:
			delta = value * 60 * 1000;
			break;
	}

	return new Date(now - delta).toISOString();
}

function createFeedItem(event: ActivityEvent, index: number): DataFeedItemSchema {
	const additionalProperty: PropertyValueSchema[] = [];

	if (event.impact) {
		additionalProperty.push({
			'@type': 'PropertyValue',
			name: 'Impact',
			value: event.impact,
		});
	}

	if (event.tags && event.tags.length > 0) {
		additionalProperty.push({
			'@type': 'PropertyValue',
			name: 'Tags',
			value: event.tags.join(', '),
		});
	}

	return {
		'@type': 'DataFeedItem',
		position: index + 1,
		dateCreated: timeAgoToIso(event.timeAgo),
		item: {
			'@type': 'Thing',
			name: `${event.label} - ${event.actor}`.trim(),
			description: event.action,
			additionalProperty: additionalProperty.length > 0 ? additionalProperty : undefined,
		},
	};
}

export function buildActivityFeedSchema(
	events: ActivityEvent[],
	options: { url?: string; description?: string } = {}
): DataFeedSchema {
	const canonicalUrl = options.url
		? buildAbsoluteUrl(options.url)
		: `${defaultSeo.canonical}#live-activity-stream`;

	const feedDescription =
		options.description ?? 'Live activity notifications generated by DealScale automation.';

	return {
		'@context': SCHEMA_CONTEXT,
		'@type': 'DataFeed',
		'@id': FEED_ID,
		name: 'DealScale Live Activity Notifications',
		description: feedDescription,
		url: canonicalUrl,
		provider: {
			'@type': 'Organization',
			name: companyData.companyName,
			'@id': ORGANIZATION_ID,
			url: defaultSeo.canonical,
		},
		dataFeedElement: events.map(createFeedItem),
	};
}
