import { DEFAULT_SEO, STATIC_SEO_META } from '@/data/constants/seo';
import { buildLegalSeoMetaMap } from './legalSeo';
import type { SeoMeta } from './seo';

export const defaultSeo: SeoMeta = {
	title: DEFAULT_SEO.title,
	description: DEFAULT_SEO.description,
	canonical: DEFAULT_SEO.canonical,
	keywords: DEFAULT_SEO.keywords,
	image: DEFAULT_SEO.image,
	siteName: DEFAULT_SEO.siteName,
	type: DEFAULT_SEO.type,
};

export const staticSeoMeta: Record<string, SeoMeta> = {
	'/': {
		title: STATIC_SEO_META['/'].title,
		description: STATIC_SEO_META['/'].description,
		canonical: STATIC_SEO_META['/'].canonical,
		image: STATIC_SEO_META['/'].image,
		keywords: DEFAULT_SEO.keywords,
		priority: 1,
		changeFrequency: 'daily',
		siteName: DEFAULT_SEO.siteName,
		type: DEFAULT_SEO.type,
	},
	'/about': {
		title: STATIC_SEO_META['/about'].title,
		description: STATIC_SEO_META['/about'].description,
		canonical: STATIC_SEO_META['/about'].canonical,
		image: STATIC_SEO_META['/about'].image,
		keywords: STATIC_SEO_META['/about'].keywords || DEFAULT_SEO.keywords,
		manifestoSections: STATIC_SEO_META['/about'].manifestoSections,
		siteName: DEFAULT_SEO.siteName,
		type: 'website',
	},
	'/products': STATIC_SEO_META['/products'] ?? {
		priority: 0.8,
		changeFrequency: 'weekly',
		title: 'Products | Deal Scale',
		description: 'Browse our curated collection of digital and physical products from Deal Scale.',
		canonical: 'https://dealscale.io/products',
		image: DEFAULT_SEO.image,
		keywords: [...DEFAULT_SEO.keywords, 'products', 'shop', 'catalog'],
		siteName: DEFAULT_SEO.siteName,
		type: DEFAULT_SEO.type,
	},
	'/privacy': {
		priority: 0.5,
		changeFrequency: 'monthly',
		title: STATIC_SEO_META['/privacy'].title,
		description: STATIC_SEO_META['/privacy'].description,
		canonical: STATIC_SEO_META['/privacy'].canonical,
		image: STATIC_SEO_META['/privacy'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/blogs': {
		priority: 0.8,
		changeFrequency: 'weekly',
		title: STATIC_SEO_META['/blogs'].title,
		description: STATIC_SEO_META['/blogs'].description,
		canonical: STATIC_SEO_META['/blogs'].canonical,
		image: STATIC_SEO_META['/blogs'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/case-studies': {
		priority: 0.8,
		changeFrequency: 'weekly',
		title: STATIC_SEO_META['/case-studies'].title,
		description: STATIC_SEO_META['/case-studies'].description,
		canonical: STATIC_SEO_META['/case-studies'].canonical,
		image: STATIC_SEO_META['/case-studies'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/contact': {
		priority: 0.7,
		changeFrequency: 'monthly',
		title: STATIC_SEO_META['/contact'].title,
		description: STATIC_SEO_META['/contact'].description,
		canonical: STATIC_SEO_META['/contact'].canonical,
		image: STATIC_SEO_META['/contact'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/contact-pilot': {
		priority: 0.7,
		changeFrequency: 'monthly',
		title: STATIC_SEO_META['/contact-pilot'].title,
		description: STATIC_SEO_META['/contact-pilot'].description,
		canonical: STATIC_SEO_META['/contact-pilot'].canonical,
		image: STATIC_SEO_META['/contact-pilot'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/cookies': {
		priority: 0.3,
		changeFrequency: 'yearly',
		title: STATIC_SEO_META['/cookies'].title,
		description: STATIC_SEO_META['/cookies'].description,
		canonical: STATIC_SEO_META['/cookies'].canonical,
		image: STATIC_SEO_META['/cookies'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/events': {
		title: STATIC_SEO_META['/events'].title,
		description: STATIC_SEO_META['/events'].description,
		canonical: STATIC_SEO_META['/events'].canonical,
		image: STATIC_SEO_META['/events'].image,
		keywords: DEFAULT_SEO.keywords,
		priority: 0.8,
		changeFrequency: 'weekly',
	},
	'/faqs': {
		title: STATIC_SEO_META['/faqs'].title,
		description: STATIC_SEO_META['/faqs'].description,
		canonical: STATIC_SEO_META['/faqs'].canonical,
		image: STATIC_SEO_META['/faqs'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/partners': {
		title: STATIC_SEO_META['/partners'].title,
		description: STATIC_SEO_META['/partners'].description,
		canonical: STATIC_SEO_META['/partners'].canonical,
		image: STATIC_SEO_META['/partners'].image,
		keywords: DEFAULT_SEO.keywords,
		priority: 0.7,
		changeFrequency: 'monthly',
	},
	'/affiliate': {
		title: STATIC_SEO_META['/affiliate'].title,
		description: STATIC_SEO_META['/affiliate'].description,
		canonical: STATIC_SEO_META['/affiliate'].canonical,
		image: STATIC_SEO_META['/affiliate'].image,
		keywords: STATIC_SEO_META['/affiliate'].keywords || DEFAULT_SEO.keywords,
		priority: STATIC_SEO_META['/affiliate'].priority ?? 0.75,
		changeFrequency: STATIC_SEO_META['/affiliate'].changeFrequency ?? 'monthly',
		siteName: DEFAULT_SEO.siteName,
		type: 'website',
	},
	'/external-tools/roi-simulator': {
		title: STATIC_SEO_META['/external-tools/roi-simulator'].title,
		description: STATIC_SEO_META['/external-tools/roi-simulator'].description,
		canonical: STATIC_SEO_META['/external-tools/roi-simulator'].canonical,
		image: STATIC_SEO_META['/external-tools/roi-simulator'].image,
		keywords: STATIC_SEO_META['/external-tools/roi-simulator'].keywords,
		priority: STATIC_SEO_META['/external-tools/roi-simulator'].priority ?? 0.85,
		changeFrequency: STATIC_SEO_META['/external-tools/roi-simulator'].changeFrequency ?? 'weekly',
		siteName: DEFAULT_SEO.siteName,
		type: DEFAULT_SEO.type,
	},
	'/careers': {
		title: STATIC_SEO_META['/careers'].title,
		description: STATIC_SEO_META['/careers'].description,
		canonical: STATIC_SEO_META['/careers'].canonical,
		image: STATIC_SEO_META['/careers'].image,
		keywords: DEFAULT_SEO.keywords,
		priority: 0.65,
		changeFrequency: 'weekly',
	},
	'/pricing': {
		title: STATIC_SEO_META['/pricing'].title,
		description: STATIC_SEO_META['/pricing'].description,
		canonical: STATIC_SEO_META['/pricing'].canonical,
		image: STATIC_SEO_META['/pricing'].image,
		keywords: DEFAULT_SEO.keywords,
		priority: STATIC_SEO_META['/pricing'].priority ?? 0.9,
		changeFrequency: STATIC_SEO_META['/pricing'].changeFrequency ?? 'daily',
	},
	'/portfolio': {
		title: STATIC_SEO_META['/portfolio'].title,
		description: STATIC_SEO_META['/portfolio'].description,
		canonical: STATIC_SEO_META['/portfolio'].canonical,
		image: STATIC_SEO_META['/portfolio'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/features': {
		title: STATIC_SEO_META['/features'].title,
		description: STATIC_SEO_META['/features'].description,
		canonical: STATIC_SEO_META['/features'].canonical,
		image: STATIC_SEO_META['/features'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/tos': {
		title: STATIC_SEO_META['/tos'].title,
		description: STATIC_SEO_META['/tos'].description,
		canonical: STATIC_SEO_META['/tos'].canonical,
		image: STATIC_SEO_META['/tos'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/GDPR': {
		title: STATIC_SEO_META['/GDPR'].title,
		description: STATIC_SEO_META['/GDPR'].description,
		canonical: STATIC_SEO_META['/GDPR'].canonical,
		image: STATIC_SEO_META['/GDPR'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/hippa': {
		title: STATIC_SEO_META['/hippa'].title,
		description: STATIC_SEO_META['/hippa'].description,
		canonical: STATIC_SEO_META['/hippa'].canonical,
		image: STATIC_SEO_META['/hippa'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/PII': {
		title: STATIC_SEO_META['/PII'].title,
		description: STATIC_SEO_META['/PII'].description,
		canonical: STATIC_SEO_META['/PII'].canonical,
		image: STATIC_SEO_META['/PII'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/tcpCompliance': {
		title: STATIC_SEO_META['/tcpCompliance'].title,
		description: STATIC_SEO_META['/tcpCompliance'].description,
		canonical: STATIC_SEO_META['/tcpCompliance'].canonical,
		image: STATIC_SEO_META['/tcpCompliance'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/legal': {
		title: STATIC_SEO_META['/legal'].title,
		description: STATIC_SEO_META['/legal'].description,
		canonical: STATIC_SEO_META['/legal'].canonical,
		image: STATIC_SEO_META['/legal'].image,
		keywords: DEFAULT_SEO.keywords,
	},
	'/linktree': {
		title: STATIC_SEO_META['/linktree'].title,
		description: STATIC_SEO_META['/linktree'].description,
		canonical: STATIC_SEO_META['/linktree'].canonical,
		image: STATIC_SEO_META['/linktree'].image,
		keywords: STATIC_SEO_META['/linktree'].keywords || DEFAULT_SEO.keywords,
		priority: 0.7,
		changeFrequency: 'daily', // Links update frequently from Notion
	},
	'/demos/real-time-analytics': {
		title: STATIC_SEO_META['/demos/real-time-analytics'].title,
		description: STATIC_SEO_META['/demos/real-time-analytics'].description,
		canonical: STATIC_SEO_META['/demos/real-time-analytics'].canonical,
		image: STATIC_SEO_META['/demos/real-time-analytics'].image,
		keywords: STATIC_SEO_META['/demos/real-time-analytics'].keywords || DEFAULT_SEO.keywords,
		priority: 0.6,
		changeFrequency: 'weekly',
	},
	...buildLegalSeoMetaMap(),
};

export function getStaticSeo(path: string): SeoMeta {
	return staticSeoMeta[path] || defaultSeo;
}
